### PR TITLE
Add option to start in fullscreen mode.

### PR DESCRIPTION
**Pull request by kristijanhusak**
Mapping to toggle fullscreen could be added in the future, but this looks fine for now.

### CODE REVIEW

**Comment by dzhou121** [comment]
Looks good to me. Although it doesn't make sense to me to put configure() in a different file?

**Comment by kristijanhusak** [comment]
The configure function is starting to grow, so i think putting it in the separate file cleans up code a bit.

**Comment by dzhou121** [comment]
Every file represents one component and editor.go is not that big I think.

**Comment by kristijanhusak** [comment]
Yeah that makes sense. I moved it back to editor.go

**Pull request merged**
