### PR TITLE
Feature ext-cmdline

### PR DESCRIPTION
**Pull request by dzhou121**

### CODE REVIEW

**Comment by Shougo** [comment]
This version binary will be released?

**Comment by dzhou121** [comment]
Yes, I'll release the binary under nightly. But you wouldn't actually see the external cmdline until https://github.com/neovim/neovim/pull/6162 is merged. I've made the externalised items dynamic so it can detect if your nvim binary supports the externalised item.

**Comment by Shougo** [comment]
OK.

**Comment by Shougo** [comment]
```
Unhandle event mode_info_set
panic: runtime error: index out of range

goroutine 1 [running, locked to thread]:
github.com/dzhou121/gonvim.(*Screen).put(0xc420138140, 0xc4202a8010, 0x44, 0x44)
        /media/sf_GOPATH0/src/github.com/dzhou121/gonvim/screen.go:468 +0x40d
github.com/dzhou121/gonvim.(*Editor).handleRedraw(0xc4201c65a0, 0xc4200f0800, 0x4b, 0x4b)
        /media/sf_GOPATH0/src/github.com/dzhou121/gonvim/editor.go:147 +0x347
github.com/dzhou121/gonvim.InitEditorNew.func1()
        /media/sf_GOPATH0/src/github.com/dzhou121/gonvim/editor.go:389 +0x97
github.com/dzhou121/gonvim.callbackeditorSignal_RedrawSignal(0x2b9bd90)
        /media/sf_GOPATH0/src/github.com/dzhou121/gonvim/moc.go:71 +0xb6
github.com/dzhou121/gonvim._cgoexpwrap_858f874cb8aa_callbackeditorSignal_RedrawSignal(0x2b9bd90)
        github.com/dzhou121/gonvim/_obj/_cgo_gotypes.go:769 +0x2b
github.com/dzhou121/gonvim._Cfunc_editorSignal_EventDefault(0x2b9bd90, 0x7f1350000aa0, 0x0)
        github.com/dzhou121/gonvim/_obj/_cgo_gotypes.go:347 +0x4a
github.com/dzhou121/gonvim.(*editorSignal).EventDefault.func1(0x2b9bd90, 0x7f1350000aa0, 0x7f1350000aa0)
        /media/sf_GOPATH0/src/github.com/dzhou121/gonvim/moc.go:532 +0xa3
github.com/dzhou121/gonvim.(*editorSignal).EventDefault(0xc42031a000, 0xf5c980, 0xc420316168, 0x5)
        /media/sf_GOPATH0/src/github.com/dzhou121/gonvim/moc.go:532 +0x74
github.com/dzhou121/gonvim.callbackeditorSignal_Event(0x2b9bd90, 0x7f1350000aa0, 0xc400000008)
        /media/sf_GOPATH0/src/github.com/dzhou121/gonvim/moc.go:527 +0x1c0
github.com/dzhou121/gonvim._cgoexpwrap_858f874cb8aa_callbackeditorSignal_Event(0x2b9bd90, 0x7f1350000aa0, 0x2ab5401)
        github.com/dzhou121/gonvim/_obj/_cgo_gotypes.go:860 +0x35
github.com/therecipe/qt/widgets._Cfunc_QApplication_QApplication_Exec(0x0)
        github.com/therecipe/qt/widgets/_obj/_cgo_gotypes.go:894 +0x49
github.com/therecipe/qt/widgets.QApplication_Exec(0xc4201cd2b0)
        /home/user/work/src/github.com/therecipe/qt/widgets/widgets-minimal.go:881 +0x22
github.com/dzhou121/gonvim.InitEditorNew()
        /media/sf_GOPATH0/src/github.com/dzhou121/gonvim/editor.go:475 +0x1575
main.main()
        /media/sf_GOPATH0/src/github.com/dzhou121/gonvim/cmd/gonvim/gonvim.go:15 +0x3a
```

The errors are occurred.

**Comment by dzhou121** [comment]
I seem not to be able to replicate.

**Comment by Shougo** [comment]
`gonvim -u NONE` works.

**Comment by Shougo** [comment]
I have analayzed the problem.
dein.vim is broken in gonvim.

**Comment by dzhou121** [comment]
Just updated nightly. Can you please try again.

**Comment by Shougo** [comment]
It works.  Thank you!

**Pull request merged**
